# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takeorders.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='takeorders.proto',
  package='order',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10takeorders.proto\x12\x05order\"g\n\x0cOrderMessage\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x16\n\x0e\x63ustomer_email\x18\x03 \x01(\t\x12\x1a\n\x05items\x18\x04 \x03(\x0b\x32\x0b.order.Item\"7\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x10\n\x08item_qty\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x02\"T\n\x0cMessageReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0borderStatus\x18\x02 \x01(\t\x12#\n\x08itemResp\x18\x03 \x03(\x0b\x32\x11.order.ItemStatus\"/\n\nItemStatus\x12\x0e\n\x06itemId\x18\x01 \x01(\x05\x12\x11\n\twasPlaced\x18\x02 \x01(\t\"/\n\rOrderStockMsg\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\norderStock\x18\x02 \x01(\t\"0\n\nServerList\x12\"\n\x07servers\x18\x01 \x03(\x0b\x32\x11.order.ServerPort\"&\n\nServerPort\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32z\n\x05Order\x12\x37\n\tSendOrder\x12\x13.order.OrderMessage\x1a\x13.order.MessageReply\"\x00\x12\x38\n\tTakeStock\x12\x13.order.OrderMessage\x1a\x14.order.OrderStockMsg\"\x00\x62\x06proto3'
)




_ORDERMESSAGE = _descriptor.Descriptor(
  name='OrderMessage',
  full_name='order.OrderMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='order.OrderMessage.customer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='order.OrderMessage.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customer_email', full_name='order.OrderMessage.customer_email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='order.OrderMessage.items', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=130,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='order.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='order.Item.item_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_qty', full_name='order.Item.item_qty', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost', full_name='order.Item.cost', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=187,
)


_MESSAGEREPLY = _descriptor.Descriptor(
  name='MessageReply',
  full_name='order.MessageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.MessageReply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderStatus', full_name='order.MessageReply.orderStatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemResp', full_name='order.MessageReply.itemResp', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=273,
)


_ITEMSTATUS = _descriptor.Descriptor(
  name='ItemStatus',
  full_name='order.ItemStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemId', full_name='order.ItemStatus.itemId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wasPlaced', full_name='order.ItemStatus.wasPlaced', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=322,
)


_ORDERSTOCKMSG = _descriptor.Descriptor(
  name='OrderStockMsg',
  full_name='order.OrderStockMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.OrderStockMsg.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderStock', full_name='order.OrderStockMsg.orderStock', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=371,
)


_SERVERLIST = _descriptor.Descriptor(
  name='ServerList',
  full_name='order.ServerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='servers', full_name='order.ServerList.servers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=421,
)


_SERVERPORT = _descriptor.Descriptor(
  name='ServerPort',
  full_name='order.ServerPort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='order.ServerPort.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='order.ServerPort.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=461,
)

_ORDERMESSAGE.fields_by_name['items'].message_type = _ITEM
_MESSAGEREPLY.fields_by_name['itemResp'].message_type = _ITEMSTATUS
_SERVERLIST.fields_by_name['servers'].message_type = _SERVERPORT
DESCRIPTOR.message_types_by_name['OrderMessage'] = _ORDERMESSAGE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['MessageReply'] = _MESSAGEREPLY
DESCRIPTOR.message_types_by_name['ItemStatus'] = _ITEMSTATUS
DESCRIPTOR.message_types_by_name['OrderStockMsg'] = _ORDERSTOCKMSG
DESCRIPTOR.message_types_by_name['ServerList'] = _SERVERLIST
DESCRIPTOR.message_types_by_name['ServerPort'] = _SERVERPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderMessage = _reflection.GeneratedProtocolMessageType('OrderMessage', (_message.Message,), {
  'DESCRIPTOR' : _ORDERMESSAGE,
  '__module__' : 'takeorders_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderMessage)
  })
_sym_db.RegisterMessage(OrderMessage)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'takeorders_pb2'
  # @@protoc_insertion_point(class_scope:order.Item)
  })
_sym_db.RegisterMessage(Item)

MessageReply = _reflection.GeneratedProtocolMessageType('MessageReply', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREPLY,
  '__module__' : 'takeorders_pb2'
  # @@protoc_insertion_point(class_scope:order.MessageReply)
  })
_sym_db.RegisterMessage(MessageReply)

ItemStatus = _reflection.GeneratedProtocolMessageType('ItemStatus', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSTATUS,
  '__module__' : 'takeorders_pb2'
  # @@protoc_insertion_point(class_scope:order.ItemStatus)
  })
_sym_db.RegisterMessage(ItemStatus)

OrderStockMsg = _reflection.GeneratedProtocolMessageType('OrderStockMsg', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSTOCKMSG,
  '__module__' : 'takeorders_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderStockMsg)
  })
_sym_db.RegisterMessage(OrderStockMsg)

ServerList = _reflection.GeneratedProtocolMessageType('ServerList', (_message.Message,), {
  'DESCRIPTOR' : _SERVERLIST,
  '__module__' : 'takeorders_pb2'
  # @@protoc_insertion_point(class_scope:order.ServerList)
  })
_sym_db.RegisterMessage(ServerList)

ServerPort = _reflection.GeneratedProtocolMessageType('ServerPort', (_message.Message,), {
  'DESCRIPTOR' : _SERVERPORT,
  '__module__' : 'takeorders_pb2'
  # @@protoc_insertion_point(class_scope:order.ServerPort)
  })
_sym_db.RegisterMessage(ServerPort)



_ORDER = _descriptor.ServiceDescriptor(
  name='Order',
  full_name='order.Order',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=463,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendOrder',
    full_name='order.Order.SendOrder',
    index=0,
    containing_service=None,
    input_type=_ORDERMESSAGE,
    output_type=_MESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TakeStock',
    full_name='order.Order.TakeStock',
    index=1,
    containing_service=None,
    input_type=_ORDERMESSAGE,
    output_type=_ORDERSTOCKMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDER)

DESCRIPTOR.services_by_name['Order'] = _ORDER

# @@protoc_insertion_point(module_scope)
