# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import takeorders_pb2 as takeorders__pb2


class OrderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOrder = channel.unary_unary(
                '/order.Order/SendOrder',
                request_serializer=takeorders__pb2.OrderMessage.SerializeToString,
                response_deserializer=takeorders__pb2.MessageReply.FromString,
                )
        self.TakeStock = channel.unary_unary(
                '/order.Order/TakeStock',
                request_serializer=takeorders__pb2.OrderMessage.SerializeToString,
                response_deserializer=takeorders__pb2.OrderStockMsg.FromString,
                )


class OrderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=takeorders__pb2.OrderMessage.FromString,
                    response_serializer=takeorders__pb2.MessageReply.SerializeToString,
            ),
            'TakeStock': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeStock,
                    request_deserializer=takeorders__pb2.OrderMessage.FromString,
                    response_serializer=takeorders__pb2.OrderStockMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.Order', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Order(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.Order/SendOrder',
            takeorders__pb2.OrderMessage.SerializeToString,
            takeorders__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TakeStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.Order/TakeStock',
            takeorders__pb2.OrderMessage.SerializeToString,
            takeorders__pb2.OrderStockMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
